#!/bin/bash
# Manually execute the playbook after 'vagrant up' has been run
# 'vagrant provision' does the same thing
ansible-playbook --private-key=.vagrant/machines/default/virtualbox/private_key \
                  -u vagrant \
                  -i .vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory \
                  provisioning/playbook.yml
