# -*- mode: ruby -*-
# vi: set ft=ruby :

# Specify minimum Vagrant version and Vagrant API version
Vagrant.require_version '>= 1.8.0'
VAGRANTFILE_API_VERSION = '2'

# Require 'yaml', 'fileutils', and 'erb' modules
require 'yaml'
require 'fileutils'
require 'erb'

# Read YAML file with VM details (box, CPU, RAM, IP addresses)
# Edit machines.yml to change VM configuration details
machines = YAML.load_file(File.join(File.dirname(__FILE__), 'machines.yml'))

# Maintain a list of roles and machines in that role
ansibleGroups = {};

# Create and configure the VMs
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Always use Vagrant's default insecure key
  config.ssh.insert_key = false

  # Iterate through entries in YAML file to create VMs
  machines.each_with_index do |machine, index|

    # Configure the VMs per details in machines.yml
    config.vm.define machine['name'] do |srv|

      # Don't check for box updates
      srv.vm.box_check_update = false

      # Specify the hostname of the VM
      srv.vm.hostname = machine['name']

      # Add to appropriate ansible groups
      if ansibleGroups[machine['role']] != nil
        ansibleGroups[machine['role']].push machine['name']
      else
        ansibleGroups[machine['role']] = [machine['name']]
      end

      # Specify the Vagrant box to use (use VMware box by default)
      srv.vm.box = machine['box']['vb']

      # Configure default synced folder (disable by default)
      if machine['sync_disabled'] != nil
        srv.vm.synced_folder '.', '/vagrant', disabled: machine['sync_disabled']
      else
        srv.vm.synced_folder '.', '/vagrant', disabled: true
      end #if machine['sync_disabled']

      # Assign additional private network
      if machine['ip_addr'] != nil
        srv.vm.network 'private_network', ip: machine['ip_addr']
      end # if machine['ip_addr']

      # Configure CPU & RAM per settings in machines.yml (VirtualBox)
      srv.vm.provider 'virtualbox' do |vb, override|
        vb.memory = machine['ram']
        vb.cpus = machine['vcpu']
        override.vm.box = machine['box']['vb']

      end # srv.vm.provider 'virtualbox'

      # 1.9.1 workaround for centos/7 https://github.com/mitchellh/vagrant/issues/8096
      if Vagrant::VERSION == "1.9.1" && srv.vm.box == "centos/7"
        srv.vm.provision "shell", inline: "service network restart", run: "always"
      end

      if index == machines.size - 1
        # on last machine execute ansible in parallel mode
        srv.vm.provision :ansible do |ansible|
          # Disable default limit to connect to all the machines
          ansible.limit = "all"
          ansible.playbook = "provisioning/playbook.yml"
          ansible.groups = ansibleGroups
          ansible.host_key_checking = false
          ansible.verbose = 'vvvv'
          ansible.extra_vars = {
              swarm_iface: "eth1"
            }
        end # srv.vm.provision :ansible
      end # if index == machines.size - 1

    end # config.vm.define
  end # machines.each
end # Vagrant.configure
